@contentType = application/json
@baseUrl = http://localhost:8080/tacra-api/v1

### [ GET ] profile/get/:user-id
# @name GetProfile
GET {{baseUrl}}/profile/get/dev-8e528b55-01d8-4dd6-9581-9f5f72cbb60b?displayName=Kirin%20Anthia
Content-Type: {{contentType}}

### [ POST ] profile/update-profile
# @name UpdateProfile
POST {{baseUrl}}/profile/update-profile
Content-Type: {{contentType}}

{
  "userId": "dev-8e528b55-01d8-4dd6-9581-9f5f72cbb60b",
  "displayName": "Kirin Anthia",
  "userName": "kirin_anthia",
  "bio": "Hello, I'm Kirin Anthia, a passionate software developer with a love for creating innovative solutions. I enjoy exploring new technologies and continuously improving my skills."
}