export enum ResponseStatusCode {
  SUCCESS = 'SUCCESS',

  AUTHENTICATION_FORBIDDEN = 'AUTHENTICATION_FORBIDDEN',
  AUTHENTICATION_BLOCKED = 'AUTHENTICATION_BLOCKED',

  USER_UNABLE_TO_RETRIEVE = 'USER_UNABLE_TO_RETRIEVE',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  GUARDE_FAILED = 'GUARDE_FAILED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
